name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Extism Builder
      run: curl -Ls https://raw.githubusercontent.com/extism/python-pdk/main/install.sh | bash

    - name: Build
      run: extism-py finfunc.py -o finfunc.wasm

    # Only run this step on main branch pushes (not PRs)
    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: finfunc.wasm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
